<?php
define('LANGUAGE', 'ar');
define('DIR', 'rtl');
define('SLOGAN', 'استضافة الملفات البسيطة');
define('DESCRIPTION', 'استضافة الملفات البسيطة. استضافة ملفات بلا حساب بلا حدود . مشاركة الملفات بسهولة على ستارفايل');
define('SELECTFILE', 'حدد ملف');
define('UPLOADMULTIPLEFILES', 'اسقط الملفات او انقر هنا');
define('UPLOADSINGLEFILE', 'اسقط الملف او انقر هنا');
define('UPLOADFILE', 'رفع ملف');
define('UPLOADFILES', 'رفع ملفات');
define('JAVASCRIPTWARNING', 'جافا سكريبت غير مفعل. رجاء قم بتفعيله لتفعيل جميع الميزات');
define('VPNWARNING', 'لقد اكتشفنا VPN. قد يؤدي استخدام VPN إلى تعطيل بعض الميزات.');
define('GOTOUPLOADPAGE', 'الذهاب الى صفحة الرفع');
define('RECENTS', 'الاحدث');
define('ERRORS', 'الأخطاء');
define('NOFILEUPLOADED', 'لم يتم رفع ملف');
define('FILETOOLARGE', 'حجم الملف كبير جدًا');
define('SERVERERROR', 'خطأ في الخادم');
define('PARTIALLYUPLOADED', 'مرفوع جزئيًا');
define('SYNCPROFILES', 'مزامنة الملفات');
define('FOOTERDESCRIPTION', 'Starfiles هي خدمة مجانية لاستضافة الملفات تتيح للمستخدمين تخزين الملفات ومشاركتها بسهولة');
define('HELPTEXT', 'يرجى الإبلاغ عن أي مشاكل وإجراء طلبات لميزة جديدة عبر');
define('TOS', 'شروط الخدمة');
define('PRIVACY', 'سياسة الخصوصية');
define('API', 'API (ادوات المطور)');
define('MADEBY', 'صنع بواسطة');
define('JSHELPANDQUEUE', 'تحسينات JavaScript و نظام الطابور');
define('DESIGNERS', 'المصممين');
define('HOME', 'الصفحة الرئيسية');
define('BASICFILEUPLOAD', 'رفع ملف اساسي');
define('NAME', 'الاسم');
define('CONTENTS', 'المحتويات');
define('EXAMPLE', 'مثال');
define('CHUNKEDFILEUPLOAD', 'رفع ملف مجزء');
define('CHUNKEXPLANATION', 'يتم تقسيم الأجزاء إلى أجزاء تصل إلى 2 ميغابايت (<span class="code">2097152</span> bytes). كرر ما يلي لكل قطعة');
define('FILE', 'ملف');
define('CHUNKCOUNT', 'عدد الجزء');
define('CHUNKNUMBER', 'رقم الجزء');
define('CHUNKUSAGE', 'آخر جزء تم رفعه سيعيد معرف الملف. استخدمه مثل ذلك');
define('FILENOTFOUND', 'لم يتم العثور على الملف');
define('FILEDELETED', 'الملف محذوف');
define('PASSWORD', 'كلمة السر');
define('PASSWORDPROTECTED', 'كلمة السر محمية');
define('PASSWORDINCORRECT', 'كلمة السر غير صحيحة');
define('ENTERPASSWORD', 'ادخل كلمة سر');
define('LOGIN', 'تسجيل الدخول');
define('DIRECTURL', 'رابط مباشر');
define('DOWNLOAD', 'تنزيل');
define('DOWNLOADS', 'التنزيلات');
define('DELETE', 'حذف');
define('REMOVEFROMPROFILE', 'إزالة من ملف التعريف');
define('REPORT', 'إبلاغ عن ملف');
define('SAVE', 'حفظ');
define('TRANSLATORS', 'المترجمين');
define('PINK', 'وردي');
define('NONE', 'لا شيء');
define('YOURDATA', 'معلوماتك');