<?php
define('LANGUAGE', 'de');
define('DIR', 'ltr');
define('SLOGAN', 'Datei-Hosting einfach gemacht');
define('DESCRIPTION', 'Dateien-Hosting einfach gemacht. Ohne Account und ohne Limits. Teile Dateien gratis auf Starfiles');
define('SELECTFILE', 'Datei auswählen');
define('UPLOADMULTIPLEFILES', 'Dateien ablegen oder hier klicken');
define('UPLOADSINGLEFILE', 'Datei ablegen oder hier klicken');
define('UPLOADFILE', 'Datei hochladen');
define('UPLOADFILES', 'Dateien hochladen');
define('JAVASCRIPTWARNING', 'JavaScript ist nicht aktiviert. Bitte aktivieren sie es um alle Funktionen freizuschalten.');
define('VPNWARNING', 'Wir haben ein VPN erkannt. Ein VPN zu benutzen könnte Funktionen kaputt machen.');
define('GOTOUPLOADPAGE', 'Zur Upload-Seite');
define('RECENTS', 'Letzte Dateien');
define('ERRORS', 'Fehler');
define('NOFILEUPLOADED', 'Keine Datei hochgeladen');
define('FILETOOLARGE', 'Datei zu groß');
define('SERVERERROR', 'Server Fehler');
define('PARTIALLYUPLOADED', 'Teilweise Hochgeladen');
define('SYNCPROFILES', 'Profil synchronisieren');
define('FOOTERDESCRIPTION', 'Startfiles ist ein datei-Hosting Service der Benutzern es erlaubt Dateien einfach zu speichern und verschicken.');
define('HELPTEXT', 'Bitte berichten sie Fehler und fragen nach neuen Features auf ');
define('TOS', 'Nutzungsbedingungen');
define('PRIVACY', 'Datenschutz-Bestimmungen');
define('API', 'API (Entwicklertools)');
define('MADEBY', 'Erstellt von');
define('JSHELPANDQUEUE', 'Javascript-Verbesserung & Warteschlangen-System');
define('DESIGNERS', 'Designer');
define('HOME', 'Startseite');
define('BASICFILEUPLOAD', 'Einfacher Datei Upload');
define('NAME', 'Name');
define('CONTENTS', 'Inhalt');
define('EXAMPLE', 'Beispiel');
define('CHUNKEDFILEUPLOAD', 'Aufgeteilter Datei Upload');
define('CHUNKEXPLANATION', 'Chunks werden in Chunks von bis zu 2 MB (<span class="code">2097152</span> bytes) aufgeteilt. Wiederholen Sie Folgendes für jeden Chunk');
define('FILE', 'Datei');
define('CHUNKCOUNT', 'Chunk Anzahl');
define('CHUNKNUMBER', 'Chunk Nummer');
define('CHUNKUSAGE', 'Der zuletzt hochgeladene Chunk gibt die Datei-ID wieder. Verwenden Sie es so');
define('FILENOTFOUND', 'Datei nicht gefunden');
define('FILEDELETED', 'Datei gelöscht');
define('PASSWORD', 'Passwort');
define('PASSWORDPROTECTED', 'Passwort geschützt');
define('PASSWORDINCORRECT', 'Passwort inkorrekt');
define('ENTERPASSWORD', 'passwort setzen');
define('LOGIN', 'Login');
define('DIRECTURL', 'Direkte URL');
define('DOWNLOAD', 'herunterladen');
define('DOWNLOADS', 'Downloads');
define('DELETE', 'Löschen');
define('REMOVEFROMPROFILE', 'Vom Profil entfernen');
define('REPORT', 'Datei melden');
define('SAVE', 'Speichern');
define('TRANSLATORS', 'Übersetzer');
define('BLUE', 'Blau');
define('PINK', 'Pink');
define('RED', 'Rot');
define('OCEAN', 'Meer');
define('MARS', 'Mars');
define('BRONZE', 'Bronze');
define('SWAMP', 'Sumpf');
define('FAIRY', 'Fee');
define('RAINFOREST', 'Regenwald');
define('NONE', 'Keine');
define('YOURDATA', 'Deine Daten');