<?php
define('LANGUAGE', 'es');
define('SLOGAN', 'Hosting de archivos hecho simple');
define('DESCRIPTION', 'El alojamiento de archivos es simple. Alojamiento de archivos sin cuentas sin límites. Comparta archivos fácilmente de forma gratuita en Starfiles.');
define('SELECTFILE', 'Seleccione Archivo');
define('UPLOADMULTIPLEFILES', 'Suelte los archivos o haga clic aquí');
define('UPLOADSINGLEFILE', 'Suelta el archivo o haz clic aquí');
define('UPLOADFILE', 'Subir archivo');
define('UPLOADFILES', 'Subir archivos');
define('JAVASCRIPTWARNING', 'Javascript no está habilitado. Habilítelo para habilitar todas las funciones.');
define('VPNWARNING', 'Hemos detectado una VPN. Usar una VPN puede romper algunas características.');
define('GOTOUPLOADPAGE', 'Ir a la página de carga');
define('RECENTS', 'Sus recientes');
define('ERRORS', 'Errores');
define('NOFILEUPLOADED', 'Ningún archivo cargado');
define('FILETOOLARGE', 'Archivo demasiado grande');
define('SERVERERROR', 'Error del Servidor');
define('PARTIALLYUPLOADED', 'Parcialmente subido');
define('SYNCPROFILES', 'Perfiles de sincronización');
define('FOOTERDESCRIPTION', 'Starfiles es un servicio gratuito de alojamiento de archivos que permite a los usuarios almacenar archivos y compartirlos fácilmente.');
define('HELPTEXT', 'Informe cualquier problema y realice solicitudes de funciones a través de ');
define('TOS', 'Términos de servicio');
define('PRIVACY', 'Política de privacidad');
define('API', 'API (Herramientas para desarrolladores)');
define('MADEBY', 'Hecho por');
define('JSHELPANDQUEUE', 'Mejora de Javascript y sistema de colas');
define('DESIGNERS', 'Diseñadores');
define('HOME', 'Hogar');
define('BASICFILEUPLOAD', 'Carga básica de archivos'); 
define('NAME', 'Nombre');
define('CONTENTS', 'Contenido');
define('EXAMPLE', 'Ejemplo');
define('CHUNKEDFILEUPLOAD', 'Carga de archivos fragmentados');
define('CHUNKEXPLANATION', 'Los fragmentos se dividen en fragmentos de hasta 2 MB (<span class = "code"> 2097152 </span> bytes). Repita lo siguiente para cada fragmento');
define('FILE', 'expediente');
define('CHUNKCOUNT', 'recuento de trozos');
define('CHUNKNUMBER', 'número de fragmento');
define('CHUNKUSAGE', 'El último fragmento cargado devolverá la ID del archivo. Úselo así');
define('FILENOTFOUND', 'Archivo no encontrado');
define('FILEDELETED', 'Archivo eliminado');
define('PASSWORD', 'Contraseña');
define('PASSWORDPROTECTED', 'Contraseña protegida');
define('PASSWORDINCORRECT', 'Contraseña incorrecta');
define('ENTERPASSWORD', 'Ingrese una contraseña');
define('LOGIN', 'Iniciar sesión');
define('DIRECTURL', 'URL directa');
define('DOWNLOAD', 'Descargar');
define('DOWNLOADS', 'Descargas');
define('DELETE', 'Eliminar');
define('REMOVEFROMPROFILE', 'Eliminar del perfil');
define('REPORT', 'Archivo de informe');
define('SAVE', 'Salvar');
define('TRANSLATORS', 'Traductores');
define('DEFAULTCOLOUR', 'Defecto');
define('GREEN', 'Verde');
define('PINK', 'Rosado');
define('NONE', 'Ninguna');
define('YOURDATA', 'Tu Informacion');