<?php
define('LANGUAGE', 'fr');
define('SLOGAN', 'L\'hébergement de fichiers en toute simplicité');
define('DESCRIPTION', 'Hébergement de fichiers sans compte et sans limites. Partagez des fichiers facilement et gratuitement sur Starfiles.');
define('SELECTFILE', 'Sélectionnez un fichier');
define('UPLOADMULTIPLEFILES', 'Glissez-deposez vos fichiers ou cliquez pour les sélectionner et l\'envoyer.');
define('UPLOADSINGLEFILE', 'Glissez-deposez un fichier ou cliquez pour le sélectionner et l\'envoyer');
define('UPLOADFILE', 'Téléverser un fichier');
define('UPLOADFILES', 'Téléverser des fichiers');
define('JAVASCRIPTWARNING', 'Javascript n\'est pas activé. Activez-le pour activer toutes les fonctionnalités.');
define('VPNWARNING', 'Nous avons détecté que vous utilisez un VPN. Utiliser ce genre d\'outil peut désactiver certaines fonctionnalités.');
define('GOTOUPLOADPAGE', 'Aller à la page de téléversement');
define('RECENTS', 'Fichiers Récents');
define('ERRORS', 'Erreurs');
define('NOFILEUPLOADED', 'Pas de fichier envoyé.');
define('FILETOOLARGE', 'Fichier trop volumineux');
define('SERVERERROR', 'Erreur du service, merci de réessayer ultérieurement');
define('PARTIALLYUPLOADED', 'Partiellement téléchargé');
define('SYNCPROFILES', 'Profils de synchronisation');
define('FOOTERDESCRIPTION', 'Starfiles est un service d\'hébergement de fichiers qui vous autorise à envoyer des fichiers et les partager facilement.');
define('HELPTEXT', 'Merci de reporter tous les problèmes que vous encontrez et de proposer des fonctionnalités via ');
define('TOS', 'Conditions d\'utilisation');
define('PRIVACY', 'Politique de confidentialité');
define('API', 'API (Outils pour les développeurs)');
define('MADEBY', 'Créé par');
define('JSHELPANDQUEUE', 'Améliorations du Javascript et système de mise en file d\'attente');
define('DESIGNERS', 'Designers');
define('HOME', 'Accueil');
define('BASICFILEUPLOAD', 'Envoi de fichier basique');
define('NAME', 'Nom');
define('CONTENTS', 'Contenus');
define('EXAMPLE', 'Exemple');
define('CHUNKEDFILEUPLOAD', 'Envoi de fichier par morceaux');
define('CHUNKEXPLANATION', 'Les morceaux sont découpés en morceaux jusqu\'a 2MB (<span class="code">2097152</span> bytes). Répétez le même processus pour chaque morceau.');
define('FILE', 'Fichier');
define('CHUNKCOUNT', 'nombre de morceaux');
define('CHUNKNUMBER', 'numéro des morceaux');
define('CHUNKUSAGE', 'Le dernier morceau envoyé va générer l\'ID du fichier. Utilisez le comme ça');
define('FILENOTFOUND', 'Fichier non trouvé');
define('FILEDELETED', 'Fichier supprimé');
define('PASSWORD', 'Mot de passe');
define('PASSWORDPROTECTED', 'Protégé par mot de passe');
define('PASSWORDINCORRECT', 'Mot de passe incorrect');
define('ENTERPASSWORD', 'Entrez un mot de passe');
define('LOGIN', 'Connexion');
define('DIRECTURL', 'Lien direct');
define('DOWNLOAD', 'Télécharger');
define('DOWNLOADS', 'Téléchargements');
define('DELETE', 'Supprimer');
define('REMOVEFROMPROFILE', 'Retirer du profil');
define('REPORT', 'Signaler le fichier');
define('SAVE', 'Sauvegarder');
