<?php
define('LANGUAGE', 'hi');
define('DIR', 'ltr');
define('SLOGAN', 'फ़ाइल साझाकरण सरल किया गया');
define('DESCRIPTION', 'फ़ाइल साझाकरण सरल किया गया. Accountless file sharing with no limits. Share files easily for free on Starfiles.');
define('SELECTFILE', 'फ़ाइल का चयन करें');
define('UPLOADMULTIPLEFILES', 'फ़ाइलें ड्रॉप या यहाँ क्लिक करें');
define('UPLOADSINGLEFILE', 'फ़ाइल ड्रॉप या यहाँ क्लिक करें');
define('UPLOADFILE', 'दस्तावेज अपलोड करें');
define('UPLOADFILES', 'फाइल अपलोड करो');
define('JAVASCRIPTWARNING', 'जावास्क्रिप्ट सक्षम नहीं है।  कृपया सभी सुविधाओं को सक्षम करने के लिए इसे सक्षम करें।');
define('VPNWARNING', 'हमने एक वीपीएन का पता लगाया है।  वीपीएन का उपयोग करने से कुछ सुविधाएं टूट सकती हैं।');
define('GOTOUPLOADPAGE', 'अपलोड पेज पर जाएं');
define('RECENTS', 'आपकी रीसेंट');
define('YOURFILES', 'आपकी फाइलें');
define('ERRORS', 'त्रुटियाँ');
define('NOFILEUPLOADED', 'कोई फ़ाइल अपलोड नहीं की गई');
define('FILETOOLARGE', 'बहुत बड़ी फाइल');
define('SERVERERROR', 'सर्वर त्रुटि');
define('PARTIALLYUPLOADED', 'आंशिक रूप से अपलोड किया गया');
define('SYNCPROFILES', 'सिंक प्रोफाइल');
define('FOOTERDESCRIPTION', 'Starfiles एक मुफ्त फ़ाइल साझा सेवा है जो उपयोगकर्ताओं को फ़ाइलों को संग्रहीत करने और उन्हें आसानी से साझा करने की अनुमति देती है।');
define('HELPTEXT', 'कृपया किसी भी समस्या की रिपोर्ट करें और के माध्यम से सुविधा अनुरोध करें ');
define('TOS', 'सेवा की शर्तें');
define('PRIVACY', 'गोपनीयता नीति');
define('API', 'एपीआई (डेवलपर उपकरण)');
define('MADEBY', 'द्वारा निर्मित');
define('JSHELPANDQUEUE', 'जावास्क्रिप्ट सुधार और कतार प्रणाली');
define('DESIGNERS', 'डिजाइनर');
define('HOME', 'होम');
define('BASICFILEUPLOAD', 'बेसिक फाइल अपलोड');
define('NAME', 'नाम');
define('CONTENTS', 'अंतर्वस्तु');
define('EXAMPLE', 'उदाहरण');
define('CHUNKEDFILEUPLOAD', 'फ़ाइल अपलोड की गई');
define('CHUNKEXPLANATION', 'चूजों को 2MB (<span class = "code"> 2097152 </ span> बाइट्स) के टुकड़ों में विभाजित किया गया है।  प्रत्येक चंक के लिए निम्नलिखित दोहराएं');
define('FILE', 'file');
define('CHUNKCOUNT', 'चंक गिनती');
define('CHUNKNUMBER', 'चंक संख्या');
define('CHUNKUSAGE', 'अपलोड किया गया अंतिम हिस्सा फ़ाइल आईडी वापस कर देगा।  इसका इस्तेमाल ऐसे करें');
define('FILENOTFOUND', 'फाइल नहीं मिली');
define('FILEDELETED', 'फ़ाइल हटा दी गई');
define('PASSWORD', 'कुंजिका');
define('PASSWORDPROTECTED', 'पासवर्ड से सुरक्षित');
define('PASSWORDINCORRECT', 'गलत पासवर्ड');
define('ENTERPASSWORD', 'एक पासवर्ड सेट करें');
define('LOGIN', 'लॉग इन करें');
define('DIRECTURL', 'सीधा URL');
define('DOWNLOAD', 'डाउनलोड');
define('DOWNLOADS', 'डाउनलोड');
define('DELETE', 'हटाएं');
define('REMOVEFROMPROFILE', 'प्रोफ़ाइल से निकालें');
define('REPORT', 'रिपोर्ट फ़ाइल');
define('SAVE', 'सहेजें');
define('TRANSLATORS', 'अनुवादक');

define('NONE', 'कोई नहीं');
define('YOURDATA', 'आपका डेटा');