<?php
define('LANGUAGE', 'idn');
define('DIR', 'ltr');
define('SLOGAN', 'berbagi file dengan mudah');
define('DESCRIPTION', 'berbagi file dengan mudah. Berbagi file tanpa akun tanpa batas. Bagikan file dengan mudah secara gratis di Starfiles.');
define('SELECTFILE', 'Pilih File');
define('UPLOADMULTIPLEFILES', 'Masukkan File atau Klik Disini');
define('UPLOADSINGLEFILE', 'Masukkan File atau Klik Disini');
define('UPLOADFILE', 'Unggah File');
define('UPLOADFILES', 'Unggah File');
define('JAVASCRIPTWARNING', 'Javascript tidak diaktifkan. Mohon aktifkan itu untuk mengaktifkan semua fitur.');
define('VPNWARNING', 'Kami telah mendeteksi VPN. Menggunakan VPN dapat merusak beberapa fitur.');
define('GOTOUPLOADPAGE', 'Pergi ke halaman unggah');
define('RECENTS', 'Baru Saja');
define('YOURFILES', 'File Anda');
define('ERRORS', 'Kesalahan');
define('NOFILEUPLOADED', 'Tidak ada file yang diunggah');
define('FILETOOLARGE', 'File Terlalu Besar');
define('SERVERERROR', 'Server Error');
define('PARTIALLYUPLOADED', 'Diunggah Sebagian');
define('SYNCPROFILES', 'Sinkronkan Profile');
define('FOOTERDESCRIPTION', 'Starfiles adalah layanan berbagi file gratis yang memingkinkan pengguna untuk menyimpan file dan membagikannya dengan mudah.');
define('HELPTEXT', 'Laporkan masalah apa pun dan buat permintaan fitur melalui ');
define('TOS', 'Persyaratan Layanan');
define('PRIVACY', 'Kebijakan Privasi');
define('API', 'API (Alat Pengembang)');
define('MADEBY', 'Dibuat oleh');
define('JSHELPANDQUEUE', 'Perbaikan Javascript & Sistem Antrian');
define('DESIGNERS', 'Desainer');
define('HOME', 'Beranda');
define('BASICFILEUPLOAD', 'Unggahan File Dasar');
define('NAME', 'Nama');
define('CONTENTS', 'Isi');
define('EXAMPLE', 'Contoh');
define('CHUNKEDFILEUPLOAD', 'Unggahan File Terpotong');
define('CHUNKEXPLANATION', 'Potongan dibagi menjadi beberapa bagian hingga 2MB (<span class="code">2097152</span> bytes). Ulangi langkah berikut untuk setiap bagian');
define('FILE', 'file');
define('CHUNKCOUNT', 'Jumlah potongan');
define('CHUNKNUMBER', 'Nomor potongan');
define('CHUNKUSAGE', 'Potongan terakhir yang diunggah akan mengembalikan ID file. Gunakan seperti itu');
define('FILENOTFOUND', 'File Tidak Ditemukan');
define('FILEDELETED', 'File Dihapus');
define('PASSWORD', 'KATA SANDI');
define('PASSWORDPROTECTED', 'Kata Sandi dilindungi');
define('PASSWORDINCORRECT', 'Kata Sandi Salah');
define('ENTERPASSWORD', 'Setel kata sandi');
define('LOGIN', 'Masuk');
define('DIRECTURL', 'URL Lagsung');
define('DOWNLOAD', 'UNDUH');
define('DOWNLOADS', 'Unduh');
define('DELETE', 'Hapus');
define('REMOVEFROMPROFILE', 'Hapus dari profil');
define('REPORT', 'Laporkan File');
define('SAVE', 'Simpan');
define('TRANSLATORS', 'Penerjemah');
define('RAINFOREST', 'Hutan Hujan');
define('YOURDATA', 'Data Anda');
define('CREATEFOLDER', 'Buat folder');
define('SEARCH', 'Cari');
define('SORTBY', 'Urutkan berdasarkan');
define('TIME', 'Waktu');
define('NAME', 'Nama');
define('TYPE', 'Tipe');
define('SIZE', 'Ukuran');
define('DOWNLOADS', 'Unduhan');
define('UNNAMEDFOLDER', 'Folder Tanpa Nama');
define('CREDITS', 'Ucapan Terima Kasih');