<?php
define('LANGUAGE', 'vn');
define('SLOGAN', 'Chia sẻ file dễ dàng');
define('DESCRIPTION', 'Chia sẻ file dễ dàng. Host file không giới hạn mà không càn tài khoản. Chia sẻ free trên Starfiles.');
define('SELECTFILE', 'Chọn file');
define('UPLOADMULTIPLEFILES', 'Thả file vào hoặc bấm vào đây');
define('UPLOADSINGLEFILE', 'Thả file vào hoặc bấm vào đây');
define('UPLOADFILE', 'Tải file lên');
define('UPLOADFILES', 'Tải file lên');
define('JAVASCRIPTWARNING', 'Javascript hiện đang không được kích hoạt, vui lòng kích hoạt Javascript để sử dụng đầy đủ chức năng.');
define('VPNWARNING', 'Chúng tôi đã phát hiện phần mềm VPN, sử dụng VPN có thể sẽ làm hỏng một số tính năng');
define('GOTOUPLOADPAGE', 'Đến trang tải lên');
define('RECENTS', 'Gần đây');
define('ERRORS', 'Lỗi');
define('NOFILEUPLOADED', 'Không có file nào được tải lên');
define('FILETOOLARGE', 'File quá lớn');
define('SERVERERROR', 'Lỗi máy chủ');
define('PARTIALLYUPLOADED', 'File đã được tải lên một phần');
define('SYNCPROFILES', 'Đồng bộ hồ sơ');
define('FOOTERDESCRIPTION', 'Starfile là một dịch vụ host file cho phép bạn upload và chia sẻ file miễn phí.');
define('HELPTEXT', 'Vui lòng báo lỗi và yêu cầu chức năng ở ');
define('TOS', 'Điều khoản sử dụng');
define('PRIVACY', 'Chính sách bảo mật');
define('API', 'API (Công cụ cho lập trình viên)');
define('MADEBY', 'Được tạo ra bởi');
define('JSHELPANDQUEUE', 'Cải thiện Javascript và hệ thống hàng đợi');
define('DESIGNERS', 'Thiết kế:');
define('HOME', 'Trang chủ');
define('BASICFILEUPLOAD', 'Tải file lên');
define('NAME', 'Tên');
define('CONTENTS', 'Nội Dung');
define('EXAMPLE', 'Ví dụ');
define('CHUNKEDFILEUPLOAD', 'Upload file theo các mảnh');
define('CHUNKEXPLANATION', 'Mảnh của file là các phần tối đa 2MB (<span class="code">2097152</span> bytes), được lặp lại cho mỗi mảnh');
define('FILE', 'file');
define('CHUNKCOUNT', 'Số lượng mảnh');
define('CHUNKNUMBER', 'chunk number');
define('CHUNKUSAGE', 'Mảnh cuối được tải lên sẽ trả về ID file, dùng như sau:');
define('FILENOTFOUND', 'Không tìm thấy file');
define('FILEDELETED', 'File đã bị xoá');
define('PASSWORD', 'Mật khẩu');
define('PASSWORDPROTECTED', 'Được bảo vệ bởi mật khẩu');
define('PASSWORDINCORRECT', 'Sai mật khẩu');
define('ENTERPASSWORD', 'Nhập mật khẩu');
define('LOGIN', 'Đăng nhập');
define('DIRECTURL', 'URL');
define('DOWNLOAD', 'Tải');
define('DOWNLOADS', 'Số lần tải');
define('DELETE', 'Xoá');
define('REMOVEFROMPROFILE', 'Xoá khỏi  hồ sơ');
define('REPORT', 'Báo cáo file');
define('SAVE', 'Lưu');
define('TRANSLATORS', 'Phiên dịch');
define('DEFAULTCOLOUR', 'Mặc định');
define('GREEN', 'Xanh lá');
define('PINK', 'Hồng');
define('NONE', 'Không có');
define('YOURDATA', 'Dữ liệu của bạn');